language: node_js
node_js:
- 8.15.1
script: npm run coverage
after_success:
- npm run mutate
- codeclimate-test-reporter < ./reports/coverage/lcov.info
env:
  global:
  - secure: GJMnhS6zTNmElOJqzItZT7TW4RRICFs2VmccflO43IHX14dnILPBuUN/+ghuZSeJXlzMJI27JicuOHLBOcM9DJv05dbU2VNTgP7qnNzaTEziP8B1dNb1So61Htf4Yewx0Dr5hacKUfec35LLb0Sy1dUN30UO/p9+qewFSdqnMFaTd39YB0UFd16TexovVnS9wdGnUN/gpBdIDE7ZDEjvdt+hP/k2FkHOy5Mwog6fbgXL+2AfDQVN8fVhZ5ylu7Z9Y0JtK9W+CwOC0+iH8AuV8qCxLcMQp2/4v25jUoojDioD6RYACSzy1B72K0RI3odkbD84OYiiia7IGrrFxVhfKb+xQDYFoRFJKIBA4FhhWHfaq/Cybml1Ufm75F53ONewAfOJ/yvUzBsZEJlavA62isEDrcMdN+SVRm46kmKYAVQFAviJkNJNqPy9p2nvWpK9q+FaTKXPg/mhnN/anZZRyunnKTmpUk0Z8aBls4rBLjtN8u7Xivhlw8GE2T5oRPtlYLOJ6sxWpxnBJtJqMMLGlauz+ItkuXhjEkY5ak0pR/7XoNozslfuUIMpmzN0RDEtjfkn6Q1Sb1eXH9dCooBuaoFOUwog83ML0WtTKNuIuTEuYuvAjdsypfQbc9fCA46a/3D3IXs0vk8Cli7P7Nd3brfdqA5AhoJqCSC88HQbsnU=
